## LU разложение
Выполнил студент 3 курса долбаеб

In [119]:
import numpy as np
import pandas as pd

def LU(A):
    n = len(A)
    L = np.eye(n)
    U = np.zeros((n, n))

    for i in range(n):
        for j in range(n):
            Sum = 0

            if (i > j):
                for k in range(j):
                    Sum += L[i, k] * U[k, j]

                L[i, j] = (A[i, j] - Sum) / U[j, j]

            else:
                for k in range(i):
                    Sum += L[i, k] * U[k, j]

                U[i, j] = (A[i, j] - Sum)
    
    return L, U

### Тест 1

In [120]:
A = np.array([
    [2.1, -4.5, -2.0],
    [3.0, 2.5, 4.3],
    [-6.0, 3.5, 2.5]
])

b = np.array([
    [19.07],
    [3.21],
    [-18.25]
])

x_ = np.array([[1.34025], [-4.75798], [2.5771]])

print(pd.DataFrame(A))
L, U = LU(A)
print(pd.DataFrame(L @ U))

     0    1    2
0  2.1 -4.5 -2.0
1  3.0  2.5  4.3
2 -6.0  3.5  2.5
     0    1    2
0  2.1 -4.5 -2.0
1  3.0  2.5  4.3
2 -6.0  3.5  2.5


In [121]:
y = np.linalg.inv(L) @ b
x = np.linalg.inv(U) @ y

x, x_

(array([[ 1.34022645],
        [-4.75800672],
        [ 2.57775289]]),
 array([[ 1.34025],
        [-4.75798],
        [ 2.5771 ]]))

### Тест 2

In [122]:
A = np.array([
    [5, -1, -5],
    [-3, 6, 2],
    [10, -7, 0]
])

b = np.array([
    [3.2],
    [5.4],
    [-1.2]
])

x_ = np.array([[0.7297], [1.2138], [0.1531]])

print(pd.DataFrame(A))
L, U = LU(A)
print(pd.DataFrame(L @ U))

    0  1  2
0   5 -1 -5
1  -3  6  2
2  10 -7  0
      0    1    2
0   5.0 -1.0 -5.0
1  -3.0  6.0  2.0
2  10.0 -7.0  0.0


In [123]:
y = np.linalg.lstsq(L, b, rcond=None)[0] #np.linalg.inv(L) @ b
x = np.linalg.lstsq(U, y, rcond=None)[0] #np.linalg.inv(U) @ y

x, x_

(array([[ 0.81714286],
        [ 1.33877551],
        [-0.09061224]]),
 array([[0.7297],
        [1.2138],
        [0.1531]]))

### Тест 3

In [124]:
A = np.array([
    [5, 2, 3],
    [1, 6, 1],
    [3, -4, -2]
])

b = np.array([
    [3],
    [5],
    [8]
])

x_ = np.array([[2], [1], [-3]])

print(pd.DataFrame(A))
L, U = LU(A)
print(pd.DataFrame(L @ U))

   0  1  2
0  5  2  3
1  1  6  1
2  3 -4 -2
     0    1    2
0  5.0  2.0  3.0
1  1.0  6.0  1.0
2  3.0 -4.0 -2.0


In [125]:
y = np.linalg.inv(L) @ b
x = np.linalg.inv(U) @ y

x, x_

(array([[ 2.],
        [ 1.],
        [-3.]]),
 array([[ 2],
        [ 1],
        [-3]]))

### Тест 4

In [126]:
A = np.array([
    [1, 2, 1, 4],
    [2, 0, 4, 3],
    [4, 2, 2, 1],
    [-3, 1, 3, 2]
])

b = np.array([
    [13],
    [28],
    [20],
    [6]
])

x_ = np.array([[3], [-1], [4], [2]])

print(pd.DataFrame(A))
L, U = LU(A)
print(pd.DataFrame(L @ U))

   0  1  2  3
0  1  2  1  4
1  2  0  4  3
2  4  2  2  1
3 -3  1  3  2
     0    1    2    3
0  1.0  2.0  1.0  4.0
1  2.0  0.0  4.0  3.0
2  4.0  2.0  2.0  1.0
3 -3.0  1.0  3.0  2.0


In [127]:
y = np.linalg.inv(L) @ b
x = np.linalg.inv(U) @ y

x, x_

(array([[ 3.],
        [-1.],
        [ 4.],
        [ 2.]]),
 array([[ 3],
        [-1],
        [ 4],
        [ 2]]))

### Тест 5

In [128]:
A = np.array([
    [2, 1, 3],
    [11, 7, 5],
    [9, 8, 4]
])

b = np.array([
    [1],
    [-6],
    [-5]
])

x_ = np.array([[-1], [0], [1]])

print(pd.DataFrame(A))
L, U = LU(A)
print(pd.DataFrame(L @ U))

    0  1  2
0   2  1  3
1  11  7  5
2   9  8  4
      0    1    2
0   2.0  1.0  3.0
1  11.0  7.0  5.0
2   9.0  8.0  4.0


In [129]:
y = np.linalg.inv(L) @ b
x = np.linalg.inv(U) @ y

x, x_

(array([[-1.00000000e+00],
        [-1.94716038e-15],
        [ 1.00000000e+00]]),
 array([[-1],
        [ 0],
        [ 1]]))

### Резюмирование

Алгоритм LU-разложения прост и работает без косяков сам по себе

Когда дело доходит до двухэтапного решения системы, прога выплёвывает неточность. Особенно она заметна в тесте 2, я там даже решил почекать встроенными солверами, и результат впрочем-то не поменялся. Могу предположить, что выч. ошибка возникает по большей части из-за двукратного использования обратной матрицы, вычисление которой процесс не самый стабильный.

### Пункт 4 лабы

In [130]:
A = np.array([
    [13.14, -2.12, 1.17],
    [-2.12, 6.3, -2.45],
    [1.17, -2.45, 4.6]
])

b = np.array([
    [1.27],
    [2.13],
    [3.14]
])

L, U = LU(A)
y = np.linalg.inv(L) @ b
x = np.linalg.inv(U) @ y

A @ x, b, "Решение", x

(array([[1.27],
        [2.13],
        [3.14]]),
 array([[1.27],
        [2.13],
        [3.14]]),
 'Решение',
 array([[0.12996615],
        [0.80016894],
        [1.07572903]]))

In [131]:
A = np.array([
    [4.31, 0.26, 0.61, 0.27],
    [0.26, 2.32, 0.18, 0.34],
    [0.61, 0.18, 3.20, 0.31],
    [0.27, 0.34, 0.31, 5.17]
])

b = np.array([
    [1.02],
    [1],
    [1.34],
    [1.27]
])

L, U = LU(A)
y = np.linalg.inv(L) @ b
x = np.linalg.inv(U) @ y

A @ x, b, "Решение", x

(array([[1.02],
        [1.  ],
        [1.34],
        [1.27]]),
 array([[1.02],
        [1.  ],
        [1.34],
        [1.27]]),
 'Решение',
 array([[0.15331773],
        [0.35835406],
        [0.35066487],
        [0.19304791]]))

### Резюмирование 2

Я решил не писать метод квадратного корня для двух симметричных матриц, а проверить как работает LU на них. Как и ожидалось, алгоритм нашел решение, и проверка показала что точно