# QR разложение

Выполнил студент 3 курса ебалн

In [ ]:
import numpy as np

def ScalarDot(v1, v2):
    return sum([v1[_]*v2[_] for _ in range(len(v1))])

def Norm2(v):
    r = ScalarDot(v, v)**.5
    return [v_ / r for v_ in v]

def QR(A): # Метод Грама-Шмидта
    n = len(A)
    R = np.zeros((n, n))
    Q = np.zeros((n, n))
    
    for i in range(n):
        Sum = np.zeros((1,n))[0]

        for j in range(i):
            scd = ScalarDot(A[:,i], Q[:,j])
            Sum += scd * Q[:,j]
        
        u_i = A[:,i] - Sum
        q_i = Norm2(u_i)

        for k in range(n): Q[k, i] = q_i[k]

    for i in range(n):
        for j in range(n):
            if (j <= i): R[j, i] = ScalarDot(A[:,i], Q[:,j])

    return Q, R

### Тест 1

In [ ]:
A = np.array([
    [1, 2, 3],
    [4, 6, 7],
    [8, 9, 0]
])

b = np.array([
    [6],
    [12],
    [24]
])

x = np.array([
    [-11.538],
    [12.923],
    [-2.769]
])

Q, R = QR(A)
print(Q @ R - A) # Демонстрация корректной работы алгоритма (и его точности)


y = Q.T @ b
x0 = np.linalg.inv(R) @ y
print(x0 - x) # Демонстрация точности решения

[[ 0.00000000e+00 -1.77635684e-15 -1.50990331e-14]
 [ 0.00000000e+00 -2.66453526e-15  8.88178420e-15]
 [ 0.00000000e+00  1.77635684e-15 -2.32294864e-15]]
[[-4.61538461e-04]
 [ 7.69230764e-05]
 [-2.30769231e-04]]


### Тест 2

In [420]:
A = np.array([
    [6.03, 13, -17],
    [13, 29.03, -38],
    [-17, -38, 50.03]
])

b = np.array([
    [2.0909],
    [4.1509],
    [-5.1191]
])

x = np.array([
    [1.03],
    [1.03],
    [1.03]
])

Q, R = QR(A)
print(Q @ R - A)


y = Q.T @ b
x0 = np.linalg.inv(R) @ y
print(x0 - x)

[[-8.88178420e-16  4.44089210e-14  3.19744231e-14]
 [ 0.00000000e+00 -7.10542736e-15 -5.11590770e-13]
 [ 0.00000000e+00  1.42108547e-14 -3.83693077e-13]]
[[-1.92112992e-12]
 [ 7.27529148e-12]
 [ 4.88298291e-12]]


### Пункт 4

In [ ]:
A = np.array([
    [2, 0, 1],
    [0, 1, -1],
    [1, 1, 1]
])

b = np.array([
    [3],
    [0],
    [3]
])


Q, R = QR(A)

y = Q.T @ b
x0 = np.linalg.inv(R) @ y

print(x0) # Решение СЛАУ

print(A @ x0 - b) # Проверка верности решения СЛАУ

[[1.]
 [1.]
 [1.]]
[[0.00000000e+00]
 [2.22044605e-16]
 [0.00000000e+00]]


## Выводы мб

По "е-15" и тп в результатах можно сказать, что точность алгоритма довольно большая. Реализуется легко и не требует теоретических заморочек, как в других методах, кайф